max_width = 90
normalize_comments = true
imports_granularity = "Crate"
imports_layout = "Vertical"
trailing_semicolon = false
use_try_shorthand = true
edition = "2021"
use_field_init_shorthand = true
tab_spaces = 4
